import json
import timeit
from matplotlib import pyplot as plt
import numpy as np

# Step 1: Read the JSON file
with open('large-file.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

# Step 2: Modify the 'size' field in every record to the value 35
def modify_field():
    for record in data[:1000]: 
        record['size'] = 35

#Using timeit’s repeat function, time the processing of the first 1000 records 1000 times
result = timeit.repeat(modify_field, number=1000, repeat=1000)
#print(f'Average time taken to modify size field: {average_time} seconds')

#generated by chatgpt
plt.hist(result, bins=30, edgecolor='black', color='purple')
plt.xlabel('Processing Time (seconds)')
plt.ylabel('Frequency')
plt.title('Distribution of Processing Times for the First 1000 Records')
#end of chatgpt 

plt.savefig('output.3.3.png')
plt.show()



